# Generated by Django 2.2.5 on 2019-12-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRoot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64, verbose_name='根菜单标签')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64, verbose_name='权限标签')),
                ('url_path', models.CharField(max_length=256, verbose_name='路由路径')),
                ('url_name', models.CharField(max_length=128, verbose_name='路由命名')),
                ('menu_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Children', to='rbac.Permission', verbose_name='所属二级菜单')),
                ('menu_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Permission', to='rbac.MenuRoot', verbose_name='所属一级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64, unique=True, verbose_name='角色标签')),
                ('permissions', models.ManyToManyField(related_name='Role', to='rbac.Permission', verbose_name='角色权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=32, verbose_name='用户名')),
                ('Password', models.CharField(max_length=16, verbose_name='密码')),
                ('Alias', models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称')),
                ('IsAdmin', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ManyToManyField(related_name='UserProfile', to='rbac.Role', verbose_name='用户角色')),
            ],
        ),
    ]
