# Generated by Django 2.2.5 on 2019-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
